@include('templates.form.input', ['label' => 'CPF','input' => 'cpf', 'attributes' => ['placeholder' => 'CPF']])
@include('templates.form.input', ['label' => 'NAME','input' => 'name', 'attributes' => ['placeholder' => 'Name']])
@include('templates.form.input', ['label' => 'PHONE','input' => 'phone', 'attributes' => ['placeholder' => 'Phone']])
@include('templates.form.input', ['label' => 'E-MAIL','input' => 'email', 'attributes' => ['placeholder' => 'E-mail']])
@include('templates.form.password', ['label' => 'PASSWORD','input' => 'password', 'attributes' => ['placeholder' => 'Password']])
